# This is a basic workflow to help you get started with Actions

name: Sample Matrix

on:
  workflow_dispatch:
# The trigger to which the workflow will run 
jobs:
  example_matrix:
    strategy:
      matrix:
        fruit: [apple, banana]
        include:
          - fruit: apple
            shape: circle
            animal: cat
          - fruit: banana
            shape: square
            animal: dog
            
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fruit - ${{ matrix.fruit }} and shape -  ${{ matrix.shape }} and  animal ${{ matrix.animal }}
      

        
    
