# This is a basic workflow to help you get started with Actions
name: Sample Matrix

on:
  
  workflow_dispatch:
    inputs:
      users:
      description: ''
      required: true
      type: string
      
jobs:
  example_matrix:
    strategy:
      matrix: ${{inputs.users}}
                  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ matrix.project }}
      - run: echo ${{ matrix.config }}
      

        
    
