# This is a basic workflow to help you get started with Actions
name: Sample Matrix

on:
  
  workflow_dispatch:
    inputs:
      matrix_input:
        description: ''
        required: true
        type: string
  
      
jobs:
  example_matrix:
    strategy:
      matrix: 
        include:
        - project: foo
          config: Debug
        - project: bar
          config: Release
                  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ matrix.project }} ${{ matrix.config }}
      
      

        
    
